spring:
  application:
    name: ducks-service

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/ducksdb
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true